### ISSUE TITLE
Integrate code from other author

### ISSUE THREAD

**Issue by haschdl** [haschdl/dear-gen-code#1]
In favour of keeping source code in the same repository, let's merge all source code from dear-gen into a single repository. 
For the sake of speed, I propose merging 
https://github.com/regisfrias/dear-gen
into this repository.

**Comment by regisfrias** [comment]
How about the folder structure?

**Comment by haschdl** [comment]
> How about the folder structure?

I started with the structure \sketches\helsinki and \sketches\stockholm , it's now merged to master.

I also renamed all of your sketches to match the week name.   Folder structure is now a bit redundant, in the sense it repeats the name in a few places, but at least it's very explicit. 
If you have a better idea for the folder **please create a new issue.**

![image](https://user-images.githubusercontent.com/9550197/50984704-c625e180-1502-11e9-90d6-69c80ce132ea.png)
